version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"

  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file:
      - .env
